# Generated by Django 6.0.4 on 2026-04-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.CharField(default='Stück', help_text='z.B. kg, Liter, Dose, Flasche', max_length=50),
        ),
    ]
