# Generated by Django 6.0.4 on 2026-04-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Ware', 'verbose_name_plural': 'Waren'},
        ),
    ]
