# Generated by Django 6.0.4 on 2026-05-20 06:34

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goods_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1200, 1200], upload_to='goods_images/'),
        ),
    ]
